### ISSUE TITLE
Logical operators' output BUUUUG! (maybe)

### ISSUE THREAD

**Issue by Atcold** [torch/DEPRECEATED-torch7-distro#104]
Coming from Matlab, I am very used to work with _boolean_ vectors and matrix. I was trying to do the same here but I discovered (after many trials) that, since those Tensors (`a:gt(.5)` for example) are ByteTensor, they cannot be used for counting purpose without being first converted to _double_ (with `:double()`).
Say for example:

``` lua
x = torch.Tensor(1000)
y = torch.Tensor(1000)
-- some operations...
-- x = bla bla bla
-- y = bla bla bla
-- let's compute the TruePositives and TrueNegatives
a = x:gt(.5) * y:gt(.5)
b = x:lt(.5) * y:lt(.5)
Accuracy = (a + b) / 1000
```

This won't work becuase we need to operate with numbers bigger than 255, therefore the code must be changed as following:

``` lua
a = x:gt(.5):double() * y:gt(.5):double()
b = x:lt(.5):double() * y:lt(.5):double()
```

Therefore, in my opinion, all the logic operators in Torch should automatically output a DoubleTensor if not otherwise specified.

**Comment by jucor** [comment]
I ran into related troubles 2 months ago, and opened issue #95 .

**Comment by NDGuthrie** [comment]
Thanks for the heads up Alfredo - I will attempt to reproduce the error.

Best,
Nathan

**Comment by clementfarabet** [comment]
I agree, these guys should default to whatever the default type is (torch.getdefaulttensortype()).

**Comment by koraykv** [comment]
I think I will disagree :) If we had bit tensors, I would even use bit tensors :). The output of logical operator is a logical tensor.
To me, it is just natural that if you want to use a logical tensor in a non-logical operation like multiplication, it makes sense to cast it to float or double.

**Comment by clementfarabet** [comment]
So maybe the right solution would be to have auto-cast, i.e. implement cross-
type operators. This would become possible:

``` lua
t = torch.ByteTensor(100):normal()
s = torch.FloatTensor(100):normal()
t:cmul(s)
```

In this case the product would be done using floats (the highest-precision type), and then cast back to the destination type (byte).

It's quite a bit of work to get that though...

**Comment by andresy** [comment]
I agree with Koray there.

**Comment by andresy** [comment]
> In this case the product would be done using floats (the highest-precision type), and then cast back to the destination type (byte).
> 
> It's quite a bit of work to get that though...

yes, and it would slow down a lot of things too :(

**Comment by clementfarabet** [comment]
OK so let's close this :-)
