### ISSUE TITLE
Cannot torch.load() large binary files

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#105]
Hi

On Mac Os X Mountain Lion, I cannot load large (2.1GB) binary files with torch.load(), in spite of having created them with torch.save(). I get:

```
t7> return torch.load('./train_binary.th7')
/usr/local/share/torch/lua/torch/File.lua:216: unknown object
stack traceback:
    [C]: in function 'error'
    /usr/local/share/torch/lua/torch/File.lua:216: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:209: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:233: in function </usr/local/share/torch/lua/torch/File.lua:229>
    [C]: at 0x0103b99eb0
t7> 
```

even though I have loaded all classes required. I have no such problems when loading the corresponding large ASCII file (2.4GB), but that last solution is extremely slow.

Is there a fix possible, please ?

**Comment by andresy** [comment]
Best solution: get rid of Mac OS X Mountain Lion. Seriously. I do not know any decent system which would keep such a **_huge**_ known bug for so long.

https://discussions.apple.com/thread/3413139?start=15&tstart=0

**Comment by andresy** [comment]
Other alternative: I pushed a fix for this ^&*()_ system.

**Comment by jucor** [comment]
Amazing, thanks a lot ! That's indeed a _massive_ fail from Apple -- thanks for palliating to it, that's really useful.
