### ISSUE TITLE
gmake dependancy when installing torch on OSX using luarocks

### ISSUE THREAD

**Issue by bmartini** [torch/DEPRECEATED-torch7-distro#106]
I've tried installing torch on two different OSX machines using luarocks and have had them both fail because "gmake" could not be found.

Simple work around was to symbolically link "make" to "gmake".

**Comment by clementfarabet** [comment]
Yeah, I just noticed that on a new machine. This is with the default luarocks that ships with Homebrew right?
It seems to be a new issue.

**Comment by clementfarabet** [comment]
OK, apparently they fixed this in a [recent commit](https://github.com/keplerproject/luarocks/commit/73ddf616ba5b9e14979a4ab8f16702d2d502098c), but there's still no official version for it (the last luarocks is 2.0.12, and that patch came after...). So I guess we have to install Luarocks from github for now?

**Comment by bmartini** [comment]
I've just been

> ln -s /usr/bin/make /usr/local/bin/gmake

and that works for now. Depends on how long it will take for the fix to be
folded into the official version.

**Comment by jucor** [comment]
I confirm the same problem as bmartini, sovled it by installing from latest github.
