### ISSUE TITLE
Compilation Errors in OSX with GCC 4.8.0

### ISSUE THREAD

**Issue by soumith** [torch/DEPRECEATED-torch7-distro#107]
After the latest commit, I see compilation errors in the master with the new commits in OSX with GCC 4.8.0, with and without LUAJIT=1 and with "generic" blas (i.e. blas off).

Pasted are the errors below.

/Users/soumithchintala/code/torch7-source/lib/TH/THDiskFile.c:29:31: error: expected ‘;’, ‘,’ or ‘)’ before ‘ptr’
 size_t fread__(void _restrict ptr, size_t size, size_t nitems, FILE *restrict stream)
                               ^
/Users/soumithchintala/code/torch7-source/lib/TH/THDiskFile.c: In function ‘THDiskFile_readByte’:
/Users/soumithchintala/code/torch7-source/lib/TH/THDiskFile.c:288:1: warning: implicit declaration of function ‘fread__’ [-Wimplicit-function-declaration]
 READ_WRITE_METHODS(unsigned char, Byte,
 ^
make[2]: *_\* [lib/TH/CMakeFiles/TH.dir/THDiskFile.c.o] Error 1
make[1]: **\* [lib/TH/CMakeFiles/TH.dir/all] Error 2
make: **\* [all] Error 2

**Comment by soumith** [comment]
I see that it is because you use the restrict qualifier, but don't explicitly state that the C standard is C99 with -std=c99 compiler flag. You don't see this behavior with apple's shipped LLVM-based compiler.

It compiles if you add -std=c99 to the C compiler options

**Comment by andresy** [comment]
indeed, i cut and pasted the man definition
the restrict keyword is now removed
thx
