### ISSUE TITLE
Module:getParameters() does not seem to correctly handle tensors with strides not equal to one

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#112]
Module:getParameters() calculates the number of elements of the underlying storages that are not accessible by the tensors, and then compresses the flatUsedStorage so that is exactly equal to the number of accessible elements.  However, when the parameters are finally set to access flatUsedStorage via the code:

for k = 1,#parameters do
         local offset = cumSumOfHoles[parameters[k]:storageOffset()]
         parameters[k]:set(flatUsedStorage,
         parameters[k]:storageOffset() - offset,
         parameters[k]:size(),
         parameters[k]:stride())
      end

the parameters are only shifted according to their offset.  Imagine the case where one of the parameters is the result of a call to unfold(1,1,10), so only every tenth element is accessed, and 9 out of every ten elements in the storage correspond to holes.  That parameter will reference elements of flatUsedStorage well beyond the span, equal to the number of accessible elements, allocated for it.  The stride needs to be modified so that the accessed elements are consecutive.  However, this will create problems when multiple parameters reference different views of the same underlying tensor.  The safest thing would probably be to do a more conservative compression of the flattened storage.

**Comment by clementfarabet** [comment]
I actually wrote a series of tests in extra/nn/test.lua, to cover all the scenarios that I could think of. You can look at them [here](https://github.com/andresy/torch/blob/master/extra/nn/test/test.lua#L1367). There are 7 tests for now, could you add one for what you're describing?

**Comment by rolfe** [comment]
This test should fail:

function nntest.Module_getParameters_8()
   local n = nn.Sequential()
   local firstLinear = nn.Linear(10,10)
   local secondLinear = nn.Linear(10,1000)
   local largeTensor = torch.Tensor(10,10,10):zero()
   local tensorSlice = largeTensor:select(2,5)
   firstLinear.weight:set(tensorSlice)
   n:add(firstLinear)
   n:add(secondLinear)
   local p = n:getParameters()

   secondLinear.weight:zero()
   --print(secondLinear.weight:sum())
   firstLinear.weight:fill(1)
   --print(secondLinear.weight:sum())

   mytester:asserteq((secondLinear.weight:sum(), 0, 'getParameters(): flattening wrong')
end
