### ISSUE TITLE
PRINT function with control of levels to print

### ISSUE THREAD

**Issue by carltonchu1** [torch/DEPRECEATED-torch7-distro#126]
The new print function prints the contents of the table in multiple depth. But sometimes the information it prints out is too much, and I would like to use the old print function sometimes. It will be great if the level of details to be printed can be selected.

**Comment by clementfarabet** [comment]
Yeah, I agree, but I don't have a good idea on how to deal with that. print() is already quite overloaded. Do you havea  an idea on how to do this cleanly?

**Comment by koraykv** [comment]
How about we add a function like torch.setprintlevel(n).
n=0 gives the standard lua print
n=4 is default is gives the current behaviour of at most 4 nested tables.
...

Is this acceptable?

**Comment by clementfarabet** [comment]
Yeah that could work nicely actually... From memory, I think I'm using a max level already, which is probably hard coded to 4 :-).

**Comment by koraykv** [comment]
OK, I'll that tomorrow.

**Comment by koraykv** [comment]
I pushed a modification that adds setprintlevel(n) function. For n=0, the print function returns to original lua print function.

**Comment by clementfarabet** [comment]
Cool and the default is still the same?

**Comment by koraykv** [comment]
yep, it is n=5 case.

**Comment by clementfarabet** [comment]
Great!, thanks for doing this.  

Clément
