### ISSUE TITLE
CUDA does not work with random

### ISSUE THREAD

**Issue by abeschneider** [torch/DEPRECEATED-torch7-distro#13]
If do:

require 'cunn'
torch.setdefaulttensortype('torch.CudaTensor')
local value = torch.rand()

I get the following error:

[string "return torch.rand()"]:1: internal error: the default tensor type does not seem to be an actual tensor

I'm not sure if this is related to the fact that 'rand' isn't wrapped in the cutorch/TensorMath.lua.

Also, the tests for cunn fail. The first error that is reported is that 'lab.randn' doesn't exist, so I replaced 'lab' with 'torch'. Once that is done, the same error as above results.

**Comment by andresy** [comment]
See comment

http://groups.google.com/group/torch7/browse_thread/thread/70977b3798a9175c
