### ISSUE TITLE
CudaTensor.pow gives NaN results for negative bases

### ISSUE THREAD

**Issue by akfidjeland** [torch/DEPRECEATED-torch7-distro#132]
For example

```
t7> print(torch.CudaTensor{-1}:pow(1))
nan
[torch.CudaTensor of dimension 1]
```

The reason for this behaviour is the use of the fast math option to nvcc (`--use_fast_math`). This results in 'pow' being replaced by the intrinsic '__powf'. This in turn is implemented as

```
__powf(x,y) = exp2f(y * __log2f(x))'.
```

as described in 'Table 7: Single-Precision Floating-Point Intrinsic Functions' in 'CUDA C Programming Guide'. Passing a negative number to '__log2f' results in NaN, hence the error.

Suggested solution:
- remove the '--use_fast_math' option completely or replace with the implied options (--prec-div=false;--prec-sqrt=false;--ftz=true;--fmad=true)
- insert manual intrinsics in places where it makes sense

**Comment by clementfarabet** [comment]
Hi Andreas,

Do you know if the removal of the --use_fast_math flag has other implications on performance?

I would go for removing it for now, but I need to do a bit of testing before.

**Comment by akfidjeland** [comment]
As far as I can tell use_fast_math only has these effects:
1. replace some functions (see below) with less precise intrinsics
2. flush denormals to zero (-ftz=true)
3. use lower-precision division (-prec-div=false)
4. use lower-precision square root (-prec-sqrt=false)
5. use fused multiply-add (-fmad=true)

This is separate from other optimizations. So, by setting the implied compiler options (2-5) appropriately the performance impact could be limited to the removal of the intrinsics.

The functions affected by (1) are:
- x/y -> __fdividef(x,y)
- sinf(x) -> __sinf(x)
- cosf(x) -> __cosf(x)
- tanf(x) -> __tanf(x)
- sincosf(x,sptr,cptr) -> __sincosf(x,sptr,cptr)
- logf(x) -> __logf(x)
- log2f(x) -> __log2f(x)
- log10f(x) -> __log10f(x)
- expf(x) -> __expf(x)
- exp10f(x) -> __exp10f(x)
- powf(x,y) -> __powf(x,y)

**Comment by clementfarabet** [comment]
OK fair enough, I've done a bit of testing on some of the benchmarks I have, and it doesn't seem to affect them much. I removed the flag ( [master](https://github.com/andresy/torch/commit/c9d192f8f4d5fcc24ae0a6d9a80256d3b5049328) ).

**Comment by lix19937** [comment]
use_fast_math  sometime let time more long
