### ISSUE TITLE
Suggestion to add raw github packages.th7 in config.th7 file

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#138]
Hi guys

Would it make sense to have torch point to the raw packages.th7 file on github, instead (or in addition to) the torch.ch version ? This could be done by adding, at install time, the line 

table.insert(pkgconfig.urls, "https://raw.github.com/andresy/torch/master/exe/torch-pkg/packages.th7")

to ~/.torch/config.th7. This would:
1. cut on the propagation delay from github to torch.ch (example discussed in  clementfarabet/graphicsmagick#3)
2. add a backup chance to install packages even if torch.ch goes down.

Or does it have some drawbacks that I'm missing?

**Comment by clementfarabet** [comment]
You're totally right, I just patched the path and changed it to [this one](https://raw.github.com/andresy/torch/master/exe/torch-pkg/packages.th7).

**Comment by jucor** [comment]
Sweet, thanks!
