### ISSUE TITLE
DataList:appendDataSet(dataSet,className) problem

### ISSUE THREAD

**Issue by hugoperlin** [torch/DEPRECEATED-torch7-distro#141]
Greatings,
I was trying to make some tests using CNN. I'm testing an binary classificator. To build the dataset, I'm using nn.DataSet and to merge the two datasets I'm using appendDataSet. The problem occour If I use different number of examples in the datasets. As 95 examples of one class and 190 examples of another class. After doing 

train = nn.DataList()
train:appendDataSet(dataSet1,'Class_1')
train:appendDataSet(dataSet2,'Class_2')

I get train:size() as been 380.
If I use the same number of examples in both two datasets, that not happen.

Any clue about that?

Thank you.

**Comment by clementfarabet** [comment]
Haven't used it in a while, but from memory it balances sampling across classes, so the virtual data set size will always be biggest class x nb classes.

**Comment by hugoperlin** [comment]
Ok, I understand now.

Thank you.
