### ISSUE TITLE
Crapy `gnuplot` `x11` terminal

### ISSUE THREAD

**Issue by Atcold** [torch/DEPRECEATED-torch7-distro#146]
The default terminal for `gnuplot` is `x11` but both Linux and Mac support the nicer `wxt`. On Linux it is installed by default, and on Mac you need just to

```
brew install gnuplot --pdf --wx --with-x
```

And then you can have a nicer output

```
a = torch.Tensor{1,2,3,2,3,2,1}
gnuplot.setterm('wxt')
gnuplot.figure(1)
gnuplot.bar(a)
gnuplot.axis({0,8,0,3.5})
gnuplot.setterm('x11')
gnuplot.figure(2)
gnuplot.bar(a)
gnuplot.axis({0,8,0,3.5})
```

![screen shot 2013-06-14 at 18 52 45](https://f.cloud.github.com/assets/2119355/657232/b8ad0940-d546-11e2-92a3-c1da0da304b4.png)

Now, is there any reason for which this is not done by default?

**Comment by koraykv** [comment]
I guess it was not available at the time. I made it take priority over x11. If you have wxt it should be the default on mac now.
