### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by hugoperlin** [torch/DEPRECEATED-torch7-distro#147]
Hi,
I'm trying to use torch with Cuda. After some issues with a simple tensor initialization, I found that my GPU does not support the **nvcc -arch=sm_20 flag**. Before change remove that flag and recompile torch from scratch, the cuda tensor basic operations worked. Now my issue is with cunn. Runing the **extra/cuda/pkg/cunn/test/test.lua**, I get the following output:

Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
Running 30 tests  
_____|________________________  ==> SpatialConvolution_backward_batch
error in conv2Dmm: invalid argument
requested grid size: 477x1x1, max allowed: 65535x65535x1
requested block size: 32x8x1, max allowed: 512x512x64
_________________|____________  ==> SpatialConvolution_backwarderror in conv2Dmv: invalid argument
___________________|__________  ==> SpatialConvolution_forward_batch
error in conv2Dmm: invalid argument
requested grid size: 546x1x1, max allowed: 65535x65535x1
requested block size: 32x8x1, max allowed: 512x512x64
_______*____________**_|___**_  ==> SpatialConvolution_forwarderror in conv2Dmv: invalid argument
____________________**_*___**_  ==> Done    

Any clue why this is happening?

Thank you.

**Comment by clementfarabet** [comment]
Hi there, well all the SpatialConvolution*\* operations require sm >= 2.0 to work... we assume a log of shared mem, which was only provided started with 2.0.
