### ISSUE TITLE
torch.add doesn't check for equal number of elements

### ISSUE THREAD

**Issue by soumith** [torch/DEPRECEATED-torch7-distro#155]
a=torch.Tensor(100)
b=torch.Tensor(200)
a:add(0.1, b) 
-- does not produce error on CPU, copies first 100 elements over
-- produces error with CUDA as the add routine there does an element check
-- behavior described in manual is consistent with the CUDA behavior

**Comment by clementfarabet** [comment]
OK I believe it's solved now. I recently introduced openmp optimizations for a few operators (div, add, mul), and it was failing to check the dimensions of the input tensors....
