### ISSUE TITLE
Tensor.add() does not check size anymore

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#157]
From the doc, for torch.add(), "The number of elements must match, but sizes do not matter." However:

``` lua
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
orLua 5.1  Copyright (C) 1994-2008 Lua.org, PUC-Rio
t7> x = torch.zeros(1,5)
t7> y = torch.ones(1,2)
t7> =x+y
 1.0000e+00  1.0000e+00 6.8028e+199 1.2218e+199  9.7280e+88
[torch.DoubleTensor of dimension 1x5]

t7> =x:numel()
5
t7> =y:numel()
2
```

Note also that the result contains some extra junk on non-matching components, too. 
This behaviour also has for side effect to make Tester:assertTensorEq() not bother about dimension checking either.

**Comment by clementfarabet** [comment]
Hi Julien, I think I fixed this yesterday, if it was the same issue as [this](https://github.com/andresy/torch/issues/155). Please just recompile, it should be handled properly now...

**Comment by jucor** [comment]
Great, thanks !
