### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by rlowrance** [torch/DEPRECEATED-torch7-distro#16]
I'm trying to install and build Torch7.

I've done the clone and installed the additional packages. After switching to the build directory, I run "cmake .." and receive these messages (lots of output omitted):

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_CXX_FLAGS) 
-- Configuring incomplete, errors occurred!

I'm probably missing something, but what?

**Comment by andresy** [comment]
It looks like CMake cannot find your C++ compiler.
Hard to say more with so little details.

**Comment by rlowrance** [comment]
Had installed gcc but not g++. Installing g++ fixed problem.
