### ISSUE TITLE
Gnuplot is not working anymore on Mac

### ISSUE THREAD

**Issue by Atcold** [torch/DEPRECEATED-torch7-distro#161]
After updating to the last version of Torch, _gnuplot_ does not work anymore on Mac

``` lua
t7> x=torch.linspace(-2*math.pi,2*math.pi)
t7> gnuplot.plot('Sin',x/math.pi,torch.sin(x),'~')
/usr/local/share/torch/lua/gnuplot/gnuplot.lua:132: Gnuplot terminal is not set
stack traceback:
        [C]: in function 'error'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:132: in function 'getfigure'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:695: in function 'figure'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:293: in function 'getCurrentPlot'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:313: in function 'writeToCurrent'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:721: in function 'gnulplot'
        /usr/local/share/torch/lua/gnuplot/gnuplot.lua:856: in function 'plot'
        [string "gnuplot.plot('Sin',x/math.pi,torch.sin(x),'~')"]:1: in main chunk
        [C]: at 0x010e7dddd0
```

**Comment by koraykv** [comment]
Thanks! Should be fixed now.

**Comment by Atcold** [comment]
Was it just about the `local` definition [here](https://github.com/andresy/torch/commit/7230d78241c6a78e4158678abed0b762801a0464)?

**Comment by koraykv** [comment]
yes

**Comment by uhotspot4** [comment]
I installed the Torch last night and its giving the following error:

> gnuplot.plot(torch.sin(x))
> /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:127: Gnuplot terminal is not set
> stack traceback:
>     [C]: in function 'error'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:127: in function 'getfigure'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:722: in function 'figure'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:288: in function 'getCurrentPlot'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:308: in function 'writeToCurrent'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:748: in function 'gnulplot'
>     /usr/local/share/lua/5.1/gnuplot/gnuplot.lua:883: in function 'plot'
>     [string "gnuplot.plot(torch.sin(x))"]:1: in main chunk
>     [C]: at 0x01071f4be0

**Comment by Atcold** [comment]
On which machine are you working? How did you install it?

**Comment by uhotspot4** [comment]
it is OS X Yosemite and I installed it using the following statements:

curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-luajit+torch | bash
luarocks install env

It was a matter of wrong lua version and gunplot not being installed properly in luarocks. It is fixed. Thanks anyway.

**Comment by Atcold** [comment]
OK, I'm glad you've manage to fix it.

P.S. It would be nice posting some more details about which "wrong version" you had installed and how _gnuplot_ (not _gnuplay_, I guess) was "not properly installed in luarocks". So, you could help others that may encounter a similar issue.

**Comment by uhotspot4** [comment]
Thanks for your followup. Honestly I don't remember how I fixed the gunplot problem but if I'm not wrong I had to reinstall the lua through brew to solve the issue. But then I ran into a new problem of Image package complaining about lua version which forced me to downgrade the lua from 5.2 to 5.1.

**Comment by Atcold** [comment]
Oh, yeah, that was it. I had this problem plenty of times!
gnu **PLOT** (not **PLAY**) gives troubles if you try to compile it with `gcc-4.9` and there is already `Lua` built with `clang`, or something similar.

**Comment by uhotspot4** [comment]
yes GNUPLOT. my spell checker changes it :)
