### ISSUE TITLE
cuda norm() 

### ISSUE THREAD

**Issue by rgoroshin** [torch/DEPRECEATED-torch7-distro#169]
The norm(p, dim) function seems to be broken for CUDA tensors. 
Try it: 
d=100
c=15 
 x = torch.rand(1,1,d,c):cuda()  
 print(x:norm(2,1))  
 print(x:float():norm(2,1))

**Comment by soumith** [comment]
i confirmed that this is indeed a bug.

**Comment by soumith** [comment]
i see completely different results for cuda and float

**Comment by rgoroshin** [comment]
It's really easy to fix. They just forgot to take the p^th root at the end.

**Comment by soumith** [comment]
can you send in a pull request?

**Comment by rgoroshin** [comment]
In FL. No laptop. Drinking

**Comment by soumith** [comment]
when back, with a laptop, and sober. do send in a pull request if you can ;)
