### ISSUE TITLE
PairwiseDistance gradInput in cuda

### ISSUE THREAD

**Issue by rgoroshin** [torch/DEPRECEATED-torch7-distro#182]
This is a small issue I noticed over the summer but forgot to report. 
The tensors in the gradInput table do not get moved to gpu memory when :cuda() is called on the module. 

t7> require 'cunn'
t7> m = nn.PairwiseDistance(1) 
t7> =m
nn.PairwiseDistance
{
  norm : 1
  gradInput : 
    {
      1 : DoubleTensor - empty
      2 : DoubleTensor - empty
    }
  output : DoubleTensor - size: 1
}
t7> m:cuda()
t7> =m
nn.PairwiseDistance
{
  norm : 1
  gradInput : 
    {
      1 : DoubleTensor - empty
      2 : DoubleTensor - empty
    }
  output : CudaTensor - size: 1
}
t7>

**Comment by soumith** [comment]
the type() function looks like it should be overloaded in pairwise distance. I'll wait until after all other issues are fixed with that module and then send in a patch.
