### ISSUE TITLE
new paths kills inline-c?

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#186]
$ torch run.lua
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
torch-qlua: /usr/local/share/torch/lua/inline/init.lua:274: attempt to call field 'pwd' (a nil value)
stack traceback:
    [C]: in function 'pwd'
    /usr/local/share/torch/lua/inline/init.lua:274: in function 'load'
    run.lua:69: in main chunk

**Comment by clementfarabet** [comment]
I think paths.cwd() does the same, and still exists!

**Comment by culurciello** [comment]
ok, but not: sys.fstat()

**Comment by clementfarabet** [comment]
Oh yes, I cleared all the filesystem functions from sys, as they were
replicated functions from either paths, penlight or lfs.

sys.fstat should be replaced by: lfs.attributes
(luarocks install luafilesystem)

**Comment by culurciello** [comment]
torch-rocks install luafilesystem
Installing http://luarocks.org/repositories/rocks/luafilesystem-1.6.2-1.src.rock...
Using http://luarocks.org/repositories/rocks/luafilesystem-1.6.2-1.src.rock... switching to 'build' mode
Archive:  /tmp/luarocks_luarocks-rock-luafilesystem-1.6.2-1-7109/luafilesystem-1.6.2-1.src.rock
  inflating: luafilesystem-1.6.2-1.rockspec
  inflating: luafilesystem-1.6.2.tar.gz
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -O2 -fPIC -I/usr/local/include/torch -c src/lfs.c -o src/lfs.o
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -bundle -undefined dynamic_lookup -all_load -o lfs.so -L/usr/local/lib src/lfs.o
ld: library not found for -lgcc_ext.10.5
collect2: error: ld returned 1 exit status

Error: Build error: Failed compiling module lfs.so

**Comment by clementfarabet** [comment]
Not sure what's going there, it builds fine for me. Note: that's not one of our packages:
[http://keplerproject.github.io/luafilesystem/](http://keplerproject.github.io/luafilesystem/)

**Comment by culurciello** [comment]
I guess "inline-c" is pretty much dead then
goodbye~

**Comment by clementfarabet** [comment]
It should be really straightfoward to get it to work again... if you guys
need it.

**Comment by itsasimiqbal** [comment]
I am facing the same problem. Is there any alternative way to use inline?

**Comment by NicholasYuan** [comment]
I changed the gcc path through bash_profile then I got no errors.

http://stackoverflow.com/questions/14694912/ld-library-not-found-for-lgcc-ext-10-5
see the second answer.

good luck.
