### ISSUE TITLE
path problem?

### ISSUE THREAD

**Issue by rlowrance** [torch/DEPRECEATED-torch7-distro#19]
I have built torch following the recipe on http://www.torch.ch/manual/install/index#development_torch_packages

When I start torch, the module 'paths' is not found:

build-isolde-lubuntu $torch
error: [string "?"]:2: module 'paths' not found:
    no field package.preload['paths']
    no file './paths.so'
    no file '/usr/local/lib/torch/paths.so'
    no file '/usr/local/lib/torch/loadall.so'

I deleted torch and re-installed and have the same problem.

I get the same problem if I install torch for all users and then attempt to run it:

build-isolde-lubuntu $/usr/local/bin/torch
error: [string "?"]:2: module 'paths' not found:
    no field package.preload['paths']
    no file './paths.so'
    no file '/usr/local/lib/torch/paths.so'
    no file '/usr/local/lib/torch/loadall.so'

My system is lubuntu 11.10.

**Comment by rlowrance** [comment]
Using the same git-clone, but building for mac os x 10.6, everything works perfectly.

**Comment by dfarmer** [comment]
You may need to run sudo ldconfig on the Linux machine to update the library cache?

**Comment by rlowrance** [comment]
After running sudo ldconfig, I have the same problem:

bin $sudo ldconfig
[sudo] password for roy: 
bin $
bin $
bin $
bin $torch
error: [string "?"]:2: module 'paths' not found:
    no field package.preload['paths']
    no file 'paths'
    no file 'paths.lua'
    no file '/home/roy/Dropbox/nyu-thesis-project/src.git/lua/paths'
    no file '/home/roy/Dropbox/nyu-thesis-project/src.git/lua/paths.lua'
    no file './paths.so'
    no file '/usr/local/lib/torch/paths.so'
    no file '/usr/local/lib/torch/loadall.so'
bin $

**Comment by rlowrance** [comment]
A work around is to put the missing libraries in the exported LUA_PATH. 

The missing libraries from my torch were these:
LUA1="/usr/local/share/torch/lua/?.lua"
LUA2="/usr/local/share/torch/lua/?/init.lua"

Then in .bashrc, one does
export LUA_PATH="${LUA1};${LUA2};<other directories>"

After restarting bash, all works fine.

I still suspect this is a bug.

(Thanks to Clement for providing the clue to solve this problem!)

**Comment by schuyler** [comment]
Relatedly, I wanted to install luarocks, and use other 3rd party lua packages with torch. Here's what I wound up having to add to my shell to get torch to recognize the libs installed by luarocks:

  export LUA_PATH="/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;;"
  export LUA_CPATH="/usr/local/lib/lua/5.1/?.so;;"

The ";;" at the end tell the Lua interpreter to tack on the compile-time default paths. (This doesn't address rlowrance's issue but I wanted to document this somewhere for other Torch users who are new to Lua.)

**Comment by rlowrance** [comment]
My problem was fixed by adding the ;; element to my LUA PATH as well.

**Comment by yonihei** [comment]
[from here](https://stackoverflow.com/questions/43348407/torch-test-sh-usr-bin-lua-module-paths-not-found)

i added . ~/torch/install/bin/torch-activate to the test.sh file at the top and it worked
