### ISSUE TITLE
Unable to find torch-qlua with Qt installed

### ISSUE THREAD

**Issue by zygmuntz** [torch/DEPRECEATED-torch7-distro#199]
I get this warning:

Unable to find torch-qlua (disabling graphics)
Fix this by installing Qt4 and rebuilding Torch7

Even though I installed Qt 4.8 from source and re-built Torch. How to fix this?

**Comment by taygunk** [comment]
It seems during the build, QT libraries are not correctly binded and torch-qlua binary is not built. After cmake command, do you see the message "QT is found" ?

**Comment by zygmuntz** [comment]
I didn't. However after deleting all from `build/` and running `cmake ..` it found Qt:

`Found Qt4: /usr/bin/qmake (found suitable version "4.7.4", required is "4.3.0")`

It seems that re-running `cmake ..` is not enough, you need to purge the build dir.

Also Qt 4.7.4 doesn't do the trick, as described here:
https://github.com/torch/torch7-tmp/issues/3

So you might consider updating some files to reflect the need for 4.8. 

I put the 4.8 `bin` dir in front of the PATH and that did the job. Problem solved, thanks.
