### ISSUE TITLE
Bug in SpatialConvolution

### ISSUE THREAD

**Issue by andresy** [torch/DEPRECEATED-torch7-distro#20]
Hey,

There is a bug in SpatialConvolution, when strides are != 1 and when the (input size - kW) is not divisible by dW
Take for e.g. a 32x32 image that you pass through a 5x5 filter with a stride dW or dH=2

When you backward, the gradInput has the wrong size: 31x31 instead of 32x32!!

Ronan

**Comment by koraykv** [comment]
It is not a bug, it is a feature :) We can check for sizes and if everything is not divisible properly, then we throw an error. However, I thought this was on purpose so that we can at least run forward for any image size. I think this was the same since torch5.

**Comment by andresy** [comment]
I think it is not a good idea to let it like that. If, for various reasons, you get different image sizes at input (that you handle somehow after the convolution), then the training is fails. Really annoying.

**Comment by koraykv** [comment]
I agree, I will put checks.

**Comment by clementfarabet** [comment]
Mmm, I really enjoyed that feature, for the forward() calls. Being able to forward any input size was convenient :-). But yeah maybe it's just being lazy, and it makes things brittle / hard to debug. Did you fix it?

**Comment by andresy** [comment]
Maybe I was not clear. I do not see any good reasons why a forward would fail if the image is not divisible properly (and, as Clement, I use it). At this time, the forward does not fail. But the backward is wrong. So there is a bug in the backward, and we should fix it.

**Comment by soumith** [comment]
a warning would be great, then you know whats wrong without losing this "feature"

**Comment by koraykv** [comment]
Now, I understand the high level temptation, however, you have to think about mechanics here. This requires cropping the input and gradInput to correct size, making a clone, doing gradient computation and then putting the clone back into place. Or am I missing an obvious solution?
