### ISSUE TITLE
Using expand wrongs computations :expand():sqrt() != :sqrt():expand()

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#200]
Hi guys

Apparently `expand` has a bug: the two tensors `z` and `y` below differ -- even though I don't think they should.

``` lua
x = torch.rand(4)
y = x:clone():resize(1,4):expand(10,4):sqrt()
z = x:clone():sqrt():resize(1,4):expand(10,4)
```

I cannot even figure where does the content of `y` come from, actually. 

Using `repeatTensor(10,1)` instead of `expand(10,4)` fixes it, but I'd rather not have this extra memory cost.

**Comment by jucor** [comment]
Thanks to @blundellc for pointing that apparently, the in-place operation (in this case `:sqrt()`, but the problem is the same with `apply` ) is applied once for each "fake" row -- thus taking the 20th root instead of the square root. 

It is kind of counter intuitive: we would expect that in-place operations on expanded tensors would apply transparently, and figure out for themselves that the tensor is the result of an expansion and would not iterate on the fake elements.

**Comment by clementfarabet** [comment]
Well so that's a general problem with tensors with weird topologies. The same is true of a tensor after an unfold operation.

Likewise, if you're expanding a tensor to sum it or multiply to another (contiguous) tensor, you really have to use the contiguous tensor as the dst tensor, otherwise results are unpredictable...

**Comment by jucor** [comment]
Except if the expanded tensor is the right-hand of the multiplication (i.e. not used to store the result).
Any chance to have those "weird" topologies supported without such surprises? Or at least raise an error in these cases?

**Comment by clementfarabet** [comment]
Right, the dst tensor has to be the contiguous one.

Catching these types of problems is a bit involve, as it would imply adding a check on all our operators?

Also in some cases it might be a desired effect, for some types of reduce operations. 
Having said that, I totally agree with you that it's a very vicious problem, that can cause subtle bugs.
