### ISSUE TITLE
:squeeze() seems undocumented

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#203]
The function `x:squeeze()` does like the similarly named Matlab function, yet I cannot find it in the Tensor documentation, nor in the Mathematical Operations documentation. Am I missing the obvious (it's Friday night, that can happen ;-) )? Is it documented somewhere else?

**Comment by andresy** [comment]
- i did not know such a matlab function existed (or maybe i checked in the past, i do not remember)
- i never took the time to document it, i am afraid
