### ISSUE TITLE
torch occasionally generating huge random numbers

### ISSUE THREAD

**Issue by soumith** [torch/DEPRECEATED-torch7-distro#205]
there seems to be a bug in the prng, where I occasionally get a gigantic number, irrespective of what range I ask for.

I noticed that this happens with torch.rand(1)[1] which gives a number out like 245381365

I also noticed that this happens with torch.uniform(1, maxvalue) where it ignores the limits and just spits out a huge number.

Anyone seen this before?
@jucor I know you've worked with developing randomkit, and work with generating fancy distributions, did you notice this ever?

This only happens after I generate quite a few random numbers.

My machine is Ubuntu 13.10 64 bit.

I'm working on creating an isolated example.

**Comment by soumith** [comment]
Also, might be of significance, I'm using threadsffi, and two threads are using the RNG for various things.

**Comment by soumith** [comment]
I created a minimal example here.
https://github.com/soumith/torch-threads-rand-bug

Please run "run.lua"

**Comment by soumith** [comment]
sometimes the problem is in the mainThread, and sometimes in the workerThread, it is not consistent.

**Comment by koraykv** [comment]
Hey Soumith,

The random number generator in TH is not thread-safe. That is why you are seeing this problem. We did some modifications to make it thread safe, but that resulted a noticeable slow-down of the random number generator. We might need to revisit the issue. There are also couple of more places in TH that this will be a problem.

**Comment by soumith** [comment]
oh i see. i guess i'll have to switch to separate processes then. thanks for the pointer.

if there's any work that needs to be done to make the RNG thread-safe while keeping it fast, feel free to assign it to me

**Comment by koraykv** [comment]
That would be fantastic, I will contact you separately.

**Comment by jucor** [comment]
Let me know if you want to re-use randomkit's RNG (that I wrapped in torch): it is also a MT, and it has a "state" structure passed as an argument, so it threadsafe by design.
