### ISSUE TITLE
'unknown object' error in the 'readObject' function while loading .net file

### ISSUE THREAD

**Issue by CharcoalApple** [torch/DEPRECEATED-torch7-distro#21]
Our system is running ubuntu 11.10. 
We've installed torch7, when we execute:
t7> network = torch.load('face.net')
(face.net is a neural network file)

we get this error:

/home/elab/testTorch/share/torch/lua/torch/File.lua:216: unknown object
stack traceback:
    [C]: in function 'error'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:216: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:209: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /home/elab/testTorch/share/torch/lua/torch/File.lua:233: in function 'load'
    [string "network = torch.load('face.net')"]:1: in main chunk
    [C]: ?

we did some digging around in File.lua, and had the program print out 'typeidx' the integer which represents the type of the object it's reading in.

 After several printouts between 0-6 (the normal range) we get one '32' which causes the program to throw the 'unknown object' error and exit.

Any suggestions?

**Comment by clementfarabet** [comment]
You need to load the 'nnx' package before loading the network, as it has
references to nnx modules. So simply do a require 'nnx' before torch.load().
On Jun 5, 2012 12:00 PM, "CharcoalApple" <
reply@reply.github.com>
wrote:

**Comment by YumiLench** [comment]
We've tried require 'nnx', but we got the same error

t7> require 'nnx'
t7> torch.load('face.net')
/usr/local/share/torch/lua/torch/File.lua:216: unknown object
stack traceback:
    [C]: in function 'error'
    /usr/local/share/torch/lua/torch/File.lua:216: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:209: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:233: in function 'load'
    [string "torch.load('face.net')"]:1: in main chunk
    [C]: ?

**Comment by clementfarabet** [comment]
OK my bad, the face.net network was stored in binary, on a 64bit machine, and I guess you're using a 32bit machine? I've just committed a new version, dumped in ASCII. You can pull the 'demos' repo, and use face.net.ascii instead. It loads like this:
network = torch.load('face.net.ascii', 'ascii')

**Comment by CharcoalApple** [comment]
That's almost definitely the issue! I actually managed to get it to run on my computer (a 64bit hp) but it wasn't working on our 32bit mac or eePC

yep, just checked it after pulling the face.net.ascii, and it works! Thanks for the quick respone

**Comment by clementfarabet** [comment]
Cool, no problem.
