### ISSUE TITLE
When applied to a 1-D Tensor, select returns a number

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#22]
The Torch documentation implies that select always returns a tensor.  However, when applied to a 1-D tensor, select returns a number rather than a Tensor.  Consider the following code:

t7> x = torch.Tensor(5):fill(1)
t7> print(x)
 1
 1
 1
 1
 1
[torch.DoubleTensor of dimension 5]

t7> print(x:select(1,3))
1
t7> print(type(x:select(1,3)))
number

**Comment by clementfarabet** [comment]
Correct. Another way of understanding select() is that select always gets rid of the dimension being selected, so the number of dimensions is always decremented after a select(). And we don't have 0-dim tensors, so we just return a number. 

If you need to keep a tensor, always, you should use narrow() instead:
t7> x = torch.Tensor(5):fill(1)
t7> print(x:narrow(1,3,1))
 1
[torch.DoubleTensor of dimension 1]

**Comment by rolfe** [comment]
Is there some way I can update the documentation to reflect this?

On Tue, Jun 5, 2012 at 5:51 PM, Clement Farabet <
reply@reply.github.com

**Comment by clementfarabet** [comment]
Yeah, so you can clone the torch repo with github, and then make your changes there. Once you're done you can do a 'pull request' so that we can merge it into the main Torch repo.
