### ISSUE TITLE
Confusing documentation for addcmul

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#23]
The documentation for Torch.addcmul seems to be misleading.  It reads:

z:addcmul(x,value,y) accumulates the result in z.

torch.addcmul(x,value,y) returns a new tensor with the result.

torch.addcmul(z,x,value,y) puts the result in z.

But the correct argument order appears to be (value,x,y)

**Comment by andresy** [comment]
indeed, i corrected that -- it should be updated soon on the torch.ch website
