### ISSUE TITLE
Element-wise max and min

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#25]
It would be really useful if torch.max(tensor, scalar) were defined to return the tensor output for which output[i] is the max of tensor[i] and scalar.  At present, the simplest ways I can see to do this are to use an apply or to create a new tensor of size matching the input, filled with the scalar.  I imagine that both of these approaches will be slower (and more memory intensive, in the second case) than a native C implementation.

**Comment by koraykv** [comment]
This is more complicated that it seems, but the following is possible.
x=torch.rand(10)
x[torch.lt(x,0.5)]=0.5

this would make any element less than 0.5 equal to 0.5 and I think satisfies what you want to do

**Comment by rolfe** [comment]
I'm a bit confused.  My reading of the documentation is that the index
operator [] takes in an n-element array-table of arguments for an
n-dimensional tensor, applies narrow to dimension i if element i of the
array-table is a scalar, and applies sub to dimension i if element i of the
array-table is an array-table of two elements.  Does it have a different
effect when the inputs are a boolean tensor?

On Tue, Jun 12, 2012 at 10:53 AM, koray kavukcuoglu <
reply@reply.github.com

**Comment by koraykv** [comment]
good point, this information is missing in the doc. you can checkout 
http://www.torch.ch/manual/torch/maths#logical_operations_on_tensors

**Comment by rolfe** [comment]
The documentation on tensor indexing seems to skip over another interesting use as well: it seems as if you can access a multidimensional tensor x using x[a][b] as well as x[{a,b}].  Only the second of these options is described.  

Am I correct in assuming that x[a], where a is a ByteTensor of the same size as x composed solely of 0 and 1, returns a new 1-D tensor that views the elements of a that are equal to 1?  Is this implemented with an array of active elements, or is the entire matrix a used?  That is, are memory and time complexity equal to the number of active elements, or the total number of elements?
