### ISSUE TITLE
Support for QT 4.8

### ISSUE THREAD

**Issue by jtbates** [torch/DEPRECEATED-torch7-distro#26]
Missing support for QT 4.8 is a problem for Ubuntu 12.04 (Precise Pangolin) as previous versions of QT are not available through the repositories.

I have not found a PPA and I'm not sure if installing QT 4.7 from source would cause problems with 4.8.  Does anyone have suggestions for a work-around?

As for adding support for QT 4.8 in Torch, what work needs to be done?  I'm confused as to why there is an issue at all since QT claims binary compatibility.

**Comment by clementfarabet** [comment]
Ok this is actually a big issue. They changed some fundamental inheritance mechanism from Qt 4.7 to 4.8. I can't even remember the exact details, but basically inheritance of some classes in our Qt wrapper aren't done properly for 4.8, and the change is non trivial...

**Comment by jtbates** [comment]
Is the offending change that virtual inheritance of QObject is no longer allowed?

**Comment by clementfarabet** [comment]
JT, let me come back to you on that. It's related to virtual inheritance indeed, but I can't remember where the problem was occurring. From memory it's in the qtluaengine.

**Comment by clementfarabet** [comment]
Ok this problem has been solved, Torch is now compatible with Qt 4.8 (thanks to Leon Bottou).

**Comment by jtbates** [comment]
Great, thanks @leonbottou !
