### ISSUE TITLE
Elements of a tensor selected with a ByteTensor cannot be set by :zero()

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#27]
Naively, I would think that indexing a tensor using a ByteTensor of zeros and ones would return a tensor that views the same underlying storage, so that methods like :zero() and :fill() would change the original tensor.  Instead, using :zero() or :fill() on a ByteTensor-indexed-tensor appears to have absolutely no effect.  On the other hand, using the equal operator on a ByteTensor-indexed-tensor performs the desired assignment.  What's going on?!?  I've included code that demonstrates this phenomenon below.

t7> x = torch.rand(10)
t7> =x
 0.2348
 0.1904
 0.9601
 0.1112
 0.2402
 0.9618
 0.1651
 0.6521
 0.4577
 0.0492
[torch.DoubleTensor of dimension 10]

t7> =x[torch.le(x,0.5)]
 0.2348
 0.1904
 0.1112
 0.2402
 0.1651
 0.4577
 0.0492
[torch.DoubleTensor of dimension 7]

t7> x[torch.le(x,0.5)]:zero()
t7> =x
 0.2348
 0.1904
 0.9601
 0.1112
 0.2402
 0.9618
 0.1651
 0.6521
 0.4577
 0.0492
[torch.DoubleTensor of dimension 10]

t7> x[torch.le(x,0.5)]:fill(0)
t7> return x
 0.2348
 0.1904
 0.9601
 0.1112
 0.2402
 0.9618
 0.1651
 0.6521
 0.4577
 0.0492
[torch.DoubleTensor of dimension 10]

t7> x[torch.le(x,0.5)] = 0
t7> return x
 0.0000
 0.0000
 0.9601
 0.0000
 0.0000
 0.9618
 0.0000
 0.6521
 0.0000
 0.0000
[torch.DoubleTensor of dimension 10]

**Comment by clementfarabet** [comment]
Jason,

Yes, good observation: the [] operator can't be overloaded to return a spase tensor, as we don't support sparse tensors. So instead, we simply overload the []= operator, as it as access to both the original tensor (x) and the binary mask (torch.le()).
Does it make sense?

**Comment by rolfe** [comment]
Hey Clement,

Thanks.  That makes sense.  I wouldn't have guessed that []= was a
monolithic operator.

Jason

On Tue, Jun 19, 2012 at 9:33 AM, Clement Farabet <
reply@reply.github.com
