### ISSUE TITLE
torch.sort(x,2) does not appear to be defined

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#31]
The documentation specifies a function torch.sort(x,2), but is unclear regarding its function.  This function does not appear to be implemented.  I suppose columns rather than rows can be sorted efficiently by transposing before and after the sort, but at the very least, it would be nice if the documentation were clearer.  

As a secondary but perhaps more important point, it would be wonderful if the documentation included the file(s) in which a function is implemented.  I think I checked all the likely spots, but I couldn't find torch.sort().

t7> help(torch.sort)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
torch.sort([resval, resind, ] x) 
 y,i=torch.sort(x) returns a tensor y of the sorted 
rows of x, and a tensor i of the corresponding indices from x.
 y,i=torch.sort(x,2) performs the sort operation for each row and
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
t7> x = torch.rand(3,5)
t7> a,b = torch.sort(x)
t7> c,d = torch.sort(x,2)
t7> print(torch.eq(a,c))
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
[torch.ByteTensor of dimension 3x5]

t7> print(torch.eq(b,d))
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
[torch.ByteTensor of dimension 3x5]

**Comment by clementfarabet** [comment]
Yeah indeed, the doc is unclear. It seems that:
torch.sort(x) is equivalent to torch.sort(x, x:dim())

so if x has 2 dims, then torch.sort(x) is the same torch.sort(x,2)...
torch.sort(x,1) does the transpose.

I've updated/changed the doc for this function.

**Comment by andresy** [comment]
actually, there is another feature for sort:

torch.sort(x,d,flag) which sorts along dimension 'd' in descending order when flag=true

just changed the dok
