### ISSUE TITLE
problem with getParameters?

### ISSUE THREAD

**Issue by abeschneider** [torch/DEPRECEATED-torch7-distro#33]
I posted this to the forums, but didn't get a response, so I thought I would try filing it as an issue.

It appears that getParameters for a module will return a tensor with shared storage. Thus, I am assuming it's correct in believing that if I change elements in the tensor returned, it should subsequently affect the parameters of the module. I can confirm this with the following code:

``` lua
local mod = nn.Linear(2, 3)
local mod2 = mod:clone('weight', 'bias', 'gradWeight', 'gradBias')
local params, gradParams = mod:getParameters()
params:fill(0)

-- this will print all 0's
print(mod2.weight) 
```

However, the weight matrix of encoder2 doesn't get updated if I do this:

``` lua
local encoder = nn.Sequential()
encoder:add(nn.Linear(2, 3))
encoder:add(nn.Tanh())

local encoder2 = encoder:clone('weight', 'bias', 'gradWeight', 'gradBias')
-- this line doesn't work correctly here
local params, gradParams = encoder:getParameters()

params:fill(0)
print(encoder2:get(1).weight) -- does not print all 0's
```

But, if I move the getParameters line above, it works as expected:

``` lua
local encoder = nn.Sequential()
encoder:add(nn.Linear(2, 3))
encoder:add(nn.Tanh())

-- when this line is moved above, the code works as expected
local params, gradParams = encoder:getParameters()
local encoder2 = encoder:clone('weight', 'bias', 'gradWeight', 'gradBias')

params:fill(0)
print(encoder2:get(1).weight) -- prints all 0's
```

**Comment by clementfarabet** [comment]
Hey thanks for reporting on this. 

This is not really a bug though. getParameters() is a bit subtle, and should be documented properly. It gets and flattens all the parameters of any given module, and insures that the set of parameters, as well as all the sharing in place **within** that module, remains consistent. In the example you show, you're grabbing the parameters of 'encoder', but getParameters doesn't know about the external encoder2. So sharing will be lost.

Here's the proper way of doing it:

``` lua
require 'nn'

encoder = nn.Sequential()
encoder:add(nn.Linear(2, 3))
encoder:add(nn.Tanh())

encoder2 = encoder:clone('weight', 'bias', 'gradWeight', 'gradBias')

consistent_module = nn.Sequential():add(encoder):add(encoder2)

params, gradParams = consistent_module:getParameters()

params:fill(0)
print( (encoder:get(1).weight - encoder2:get(1).weight):max() )
-- prints 0 !
```

So in that example, we get the parameters of a complete module, and getParameters insures that relationships are properly conserved within it.

**Comment by abeschneider** [comment]
Okay, good to know. Thanks for the explanation.

I'm still a little confused as to why sharing is long in the first example, but not the second example I gave.

**Comment by octavian-ganea** [comment]
Can you please explain more how getParameters() should be applied in the case of a single network with many layers, where some modules are constrained to be identical, but the rest not? Thanks.

**Comment by soumith** [comment]
do you have a sample definition of your network?

**Comment by octavian-ganea** [comment]
Thanks for your fast answer. I would like to have a network where the last layer gets as input a table of 10 tensors and applies the same linear layer on each of these 10 tensors. The network has other modules and parameters before this stage, but only this linear layer is shared. A code (maybe not the simplest, I apologize) :

```
require 'nn'
require 'nngraph'

input = nn.Identity()()
conv_layer = nn.ParallelTable()
for i=1,10 do
  conv_layer:add(nn.Linear(100,50))
end
m = conv_layer(input)

common_linear_layer = nn.Linear(50,1)
debug_linear = nn.Linear(50,1)

out_nums = {}
for i=1,10 do
  local slice = nn.SelectTable(i)(m)
  local mylin = common_linear_layer:clone('weight','bias', 'gradWeight', 'gradBias')  
  if i == 1 then
    debug_linear = mylin
  end
  table.insert(out_nums, mylin(slice))
end

out = nn.LogSoftMax()(nn.JoinTable(1)(out_nums))
model = nn.gModule({input}, {out})

common_linear_layer.gradWeight:add(torch.randn(1,50))
print('ok ' .. torch.norm(debug_linear.gradWeight))
print('ok ' .. torch.norm(common_linear_layer.gradWeight))
print('\n')         

model:getParameters()

common_linear_layer.gradWeight:add(torch.randn(1,50))
print('not ok ' .. torch.norm(debug_linear.gradWeight))
print('not ok ' .. torch.norm(common_linear_layer.gradWeight))
```

It's not clear to me how can I apply your solution in this case. It's also a bit weird that in the example given above by @clementfarabet the dimension of the params vector is 9 . I would have been expected this dimension to be 18 (concatenation of encoder and encoder2, each having 9 parameters) , but probably there is some more magic that happens inside getParameters() that compresses the shared parameters. It's just unclear how should my consistent_module look in this case. Thanks a lot for your help!

**Comment by octavian-ganea** [comment]
Problem solved. The module that all the copies are cloned after should also be added to the network and everything will work as expected.

**Comment by Amir-Arsalan** [comment]
@octavian-ganea Can you post your code sample? I am having trouble doing parameter sharing in the right way.

**Comment by octavian-ganea** [comment]
@Amir-Arsalan I don't have it now, but the idea is as follows: 
First, when defining your model, first define the shared module once, e.g. 
`common_linear_layer = nn.Linear(50,1)`
Further, add it to your network how many times you want using the cloned copy of it:
`some_container:add(common_linear_layer:clone('weight','bias', 'gradWeight', 'gradBias'))`
Last, call model:getParameters() in your training function. This will return a flattened vector of your parameters where the weights of common_linear_layer should appear only once (for all the shared parameters). If you want to visualize these weights, just call common_linear_layer.weight . Hope this helps.

**Comment by Amir-Arsalan** [comment]
@octavian-ganea I'm still not able to figure out how I can apply what you described in my implementation. I've posted a simplified version of my implementation [here](http://stackoverflow.com/questions/38725285/unable-to-do-parameter-sharing-in-torch-between-networks). Any hints on my implementation on what I'm doing wrong that does not let share parameters correctly is appreciated.

Update: The issue is resolved now. The solution was provided by @fmassa. Please check the link above for the solution.

**Comment by octavian-ganea** [comment]
replied to your SO post.
