### ISSUE TITLE
torch7 fails to compile with gcc 4.7, 4.4 and clang 3.1

### ISSUE THREAD

**Issue by benanne** [torch/DEPRECEATED-torch7-distro#34]
I'm trying to install torch7 on my laptop, which has a Geforce GT540M GPU. unfortunately I can't get it to compile. 'make' fails at about 96% with the following error:

https://gist.github.com/3087845

Some CUDA-related stuff seems to cause the problem.What's interesting is that the same output results when using gcc 4.4 or clang 3.1 (which I did by running 'make clean', setting the CC and CXX variables and then recompiling). So despite the fact that it's using a different compiler, it's still looking for these files from gcc 4.7.

I can just disable the CUDA-related stuff for now, but it would of course be cool to be able to use it :)

**Comment by andresy** [comment]
Given that I never had a problem with those compilers, I suspect some installation problem (gcc/clang or CUDA) on your system.

In particular, I do not see any reasons why your compilers would be using files from gcc 4.7. That does not sound good to me.
