### ISSUE TITLE
In nn.hessian.enable(), should the last few lines reset nn.hessian.enable() rather than nn.hessian.activate()?

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#35]
Is nn.hessian.activate() ever actually called?

**Comment by clementfarabet** [comment]
Just committed a patch: activate() was the old name, I've replaced it by enable().

nn.hessian.enable() is not called by default, as this code is still experimental. It is called by the 'unsup' package though, so if you require unsup, the hessian code is made available. Once we have a cleaner implementation of these hessian guys, we will get rid of enable(), and enable it all the time.

**Comment by rolfe** [comment]
It seems like some significant changes have been made to kex, and perhaps
to other packages, in the past few weeks.  Are these changes summarized
anywhere, so I can determine any interactions with my code?

On Fri, Jul 13, 2012 at 11:05 AM, Clement Farabet <
reply@reply.github.com

**Comment by clementfarabet** [comment]
The easiest way is to do : git log, in the directory of your package, to get your current version. For kex, it would go like this :
$ cd ~/.torch/packages/kex/
$ git log
That'll give you the hash code for the latest commit in your version of the code, as well as the date of that latest commit. You can then go on github's commit list, for kex it's there:
https://github.com/koraykv/kex/commits/master

On that page you can check all the things that got modified from your version.
