### ISSUE TITLE
nn.test() fails on 3 tests, one of them with significant delta

### ISSUE THREAD

**Issue by soumith** [torch/DEPRECEATED-torch7-distro#36]
Hey,

I compiled t7 on OSX Lion, I tried using OpenBlas as well as Accelerate. The nn.test() fails in the following tests. 

Running 42 tests
__________________________________________  ==> Done                                    

Completed 42 tests with 3 errors

---

Log
error on state 
 LT(<) violation   val=nan, condition=1e-05
    /usr/local/share/torch/lua/torch/Tester.lua:23: in function 'assertlt'
    /usr/local/share/torch/lua/nn/test.lua:86: in function 'f'

---

Log
nn.Log - i/o forward err 
 EQ(==) violation   val=nan, condition=0
    /usr/local/share/torch/lua/torch/Tester.lua:35: in function 'asserteq'
    /usr/local/share/torch/lua/nn/test.lua:89: in function 'f'

---

LogSoftmax
error on state 
 LT(<) violation   val=0.00010794427179567, condition=0.0001
    /usr/local/share/torch/lua/torch/Tester.lua:23: in function 'assertlt'
    /usr/local/share/torch/lua/nn/test.lua:366: in function 'f'

---

**Comment by clementfarabet** [comment]
Hey Soumith,

The LogSoftMax error is normal, as we use an approximation. It's typically in the order of 1e-5.

The Log error is really wrong, I've no idea what's happening there.
