### ISSUE TITLE
inplace range ignores select

### ISSUE THREAD

**Issue by iainmelvin** [torch/DEPRECEATED-torch7-distro#38]
> x=torch.zeros(3,2)
> torch.range(x:select(2,1),1,3)
> =x
>  1  2
>  3  0
>  0  0
> [torch.DoubleTensor of dimension 3x2]

Internally torch.range does a "resize1d" and then fills that up incrementally with the range, which might not be what the user is expecting.

**Comment by andresy** [comment]
Very good point, thanks. In fact, it impacts most tensor math functions. These functions resize the tensor if it does not have the right size. And, as a recall, resizing implies loosing strides & storage offset.

I committed a fix: when the tensor is of the right size, resize() functions do not do anything.
