### ISSUE TITLE
module:zeroGradParameter() should be m:zeroGradParameters() in line 171 of Jacobian.lua

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#39]
I think module:zeroGradParameter() should be m:zeroGradParameters() in line 171 of Jacobian.lua.
This probably doesn't have any effect in practice, since the gradients are presumably initialized to zero.  I'd fork, modify, and issue a pull request, but I'm not sure this is actually incorrect, so it seems safer for someone more familiar with the code to make the change, if required.

**Comment by koraykv** [comment]
Thanks! I corrected this, that call was actually not necessary :), that is why everything was working...
