### ISSUE TITLE
String output of NaN values

### ISSUE THREAD

**Issue by schaul** [torch/DEPRECEATED-torch7-distro#4]
A tensor containing not-a-number values cannot be printed. For example

```
print(lab.zeros(1)/0)
```

crashes. On the other hand

```
print((lab.zeros(1)/0)[1])
```

works fine, and prints out

```
-nan
```

**Comment by clementfarabet** [comment]
I've committed a fix into the master (also available in beta-clement). It should handle NaNs anywhere now.
