### ISSUE TITLE
Wrong code on Torch Tutorial

### ISSUE THREAD

**Issue by Atcold** [torch/DEPRECEATED-torch7-distro#42]
In the Torch Tutorial / Lua Basics / Function (http://www.torch.ch/manual/tutorial/index#functions) the code is wrong, i.e. it does not what it is supposed to do. There is a mismatch between what is explained and what the code effectively does (moreover, the output shown on the website is visibly different from what can be achieved just running the same script on Torch).

**Comment by koraykv** [comment]
Sorry, I wonder what went crazy there. Here is what it should be. We will update the doc soon.

myfuncs = {}
for i = 1,4 do
   local calls = 0
   myfuncs[i] = function()
      calls = calls + 1
      print('this function has been called ' .. calls .. ' times')
   end
end
