### ISSUE TITLE
cunn seems to be broken.

### ISSUE THREAD

**Issue by soumith** [torch/DEPRECEATED-torch7-distro#43]
cunn modules seem to not be replacing the nn modules when we do a torch.setdefaulttensortype('torch.CudaTensor')

What I tried:
torch.setdefaulttensortype('torch.CudaTensor')
a = nn.Sequential()
a:add( nn.SpatialConvolution(1,3,4,4))
...104/torch7/share/torch/lua/nn/SpatialConvolution.lua:31: internal error: the default tensor type does not seem to be an actual tensor
stack traceback:
        [C]: in function 'uniform'
        ...104/torch7/share/torch/lua/nn/SpatialConvolution.lua:31: in function <...104/torch7/share/torch/lua/nn/SpatialConvolution.lua:30>
        [C]: in function 'apply'
        ...ome/sc3104/torch7/share/torch/lua/cutorch/Tensor.lua:3: in function 'apply'
        ...104/torch7/share/torch/lua/nn/SpatialConvolution.lua:30: in function 'reset'
        ...104/torch7/share/torch/lua/nn/SpatialConvolution.lua:21: in function '__init'
        /home/sc3104/torch7/share/torch/lua/torch/init.lua:43: in function </home/sc3104/torch7/share/torch/lua/torch/init.lua:39>
        [C]: in function 'SpatialConvolution'
        [string "a:add( nn.SpatialConvolution(1,3,4,4))"]:1: in main chunk
        [C]: ?

**Comment by clementfarabet** [comment]
Indeed, something's been broken with the current default tensor type mechanism.

We're going to fix this soon, but in general I wouldn't recommend setting the default type as Cuda anyway: it's better to keep the default type as Float or Double, and just convert your networks, or parts of your compute graph using cuda(). The example above would become:

torch.setdefaulttensortype('torch.FloatTensor') -- or nothing

a = nn.Sequential()
a:add( nn.SpatialConvolution(1,3,4,4))
a:cuda()

-- after this line, a is a network that lives on the GPU.
