### ISSUE TITLE
torch.load() limitation in file size?

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#45]
I am trying to load a 3+GB file and get an error. Is there a limit in file size save in Torch7?

**Comment by clementfarabet** [comment]
Are you on a 32bit machine? You need to have torch compiled in 64bit to do anything above 2GB...

**Comment by culurciello** [comment]
no I am on a 64b machine

**Comment by culurciello** [comment]
when I try to save even a small portion of this struct:
trainData
{[size]   = function: 0x7fa4bf373b90
 [data]   = DoubleTensor - size: 50000x64x12x12
 [labels] = DoubleTensor - size: 50000}

with:
torch.save('trainsmall.t7', trainData.data[{{1,1}}])

it saves a 3.69GB file that is unloadable.
something wrong here in the torch.save function

**Comment by cosmozhang** [comment]
When I am using Torch.load(face.net), it occurred like this: 
run_69.c: In function ‘run_69_l’:
run_69.c:10:7: warning: ‘luaT_checktypename2id’ is deprecated (declared at /usr/local/include/torch/luaT.h:100) [-Wdeprecated-declarations]
torch-qlua: /usr/local/share/torch/lua/torch/File.lua:216: unknown object
stack traceback:
    [C]: ?
    [C]: in function 'error'
    /usr/local/share/torch/lua/torch/File.lua:216: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:210: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:196: in function 'readObject'
    /usr/local/share/torch/lua/torch/File.lua:233: in function 'load'
    run.lua:73: in main chunk
I am using a 32 machine.
Or how to dump from face.net to face.net.ascii?
Thanks.
