### ISSUE TITLE
torch.save not working

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#47]
when I try to save even a small portion of this struct:
trainData
{[size]   = function: 0x7fa4bf373b90
 [data]   = DoubleTensor - size: 50000x64x12x12
 [labels] = DoubleTensor - size: 50000}

with:
torch.save('trainsmall.t7', trainData.data[{{1,1}}])

it saves a 3.69GB file that is unloadable.
something wrong here in the torch.save function

**Comment by culurciello** [comment]
only saving like this works:
torch.save('traindata1.t7', trainData.data:float())

**Comment by culurciello** [comment]
it generates a 1.84GB file but it can be laoded and works

**Comment by andresy** [comment]
bizarre... on my computer it works fine. i also get the 3.69GB file, but it loads. what is the error you get?

**Comment by leonbottou** [comment]
I suspect that he compiled torch in 32 bits mode.

Then files above 2GB are problematic unless you compile with option -D_FILE_OFFSET_BITS=64.

Also you should use fseeko() and ftello() to seek into the file using 64 bit off_t positions instead of 32 bits long positions…
- L.

**Comment by culurciello** [comment]
Thank you guys. I am on a 64 machine/built.
I run 3 tests saving a 800MB, 3.2GB and 4GB files - all works (see below).
This means the issue I hade above is due to saving structures of data, not one single tensor. 

t7> a = torch.randn(100000000)
t7> =a[23]
2.7746021913159
t7> torch.save('testsave.t7', a)
t7> b=torch.load('testsave.t7')
t7> =b:size()
 100000000
[torch.LongStorage of size 1]
t7> return b[23]
2.7746021913159

t7> a = torch.randn(400000000)
t7> return a[23]
1.6885985839341
t7> torch.save('testsave2.t7', a)
t7> b=torch.load('testsave2.t7')
t7> return b:size()
 400000000
[torch.LongStorage of size 1]
t7> return b[23]
1.6885985839341

t7> a = torch.randn(500000000)
t7> return a[23]
1.4147438128033
t7> torch.save('testsave3.t7', a)
t7> b=torch.load('testsave3.t7')
t7> return b:size()
 500000000
[torch.LongStorage of size 1]
t7> return b[23]
1.4147438128033

**Comment by culurciello** [comment]
hi guys, what is teh best way to save a trained network? I use torch.save, but it saves 100s of MB or GB of data!!!! too much. How can we just save the network and its parameters only?

**Comment by clementfarabet** [comment]
This has always been an issue for me as well, because all the states of the
network ate serialized as well. The only workaround I found was to create
two networks, one that's trained, and the other one that remains empty.
Then each time you want to save, you copy the trained parameters into the
empty network, and save it. It'll be really small on disk...

**Comment by andresy** [comment]
Yep, the serialization stuff saves everything you have in your network. What probably takes space in your case are the output/gradInput that you might not want to keep on disk.

So when I want to save only the parameters I do something like:
netsav = network:clone('weight', 'bias'),
right after creating my network.

This mean I now have a network with empty state (no gradInput/output), but "pointing" on the weights of my initial network.

I train the "network" normally, and save "netsav". Easy, no? ;)

**Comment by andresy** [comment]
in fact i think you can do just something like: torch.save('network.t7', network:clone('weight', 'bias'))
the clone will be then garbage-collected

**Comment by clementfarabet** [comment]
Ronan, your first solution rocks, its really clean, but the second doesn't,
because the clone will clone the states then right?

**Comment by andresy** [comment]
oops, yeah, sorry, i smoked. the first one is indeed simple and is 100% tested ;)

**Comment by culurciello** [comment]
Hi Ronan, yes I saw that trick in Torch manual. But I want to save a TRAINED net!!! That is the point, right? So the only option is a script that clones the net and copies only the weights, biases...

**Comment by clementfarabet** [comment]
Eugenio, the first solution Ronan gave will save your trained network. When you do:

emptynet = network:clone('weight','bias')

it shares the weights and biases. So later on, if you train 'network', saving 'emptynet' will save the trained parameters, but not the states...

Clement.

**Comment by culurciello** [comment]
I see. I was trying to load a large net, doing clone and then saving again. I got same file size.

**Comment by clementfarabet** [comment]
No, but you have to clone the network before it ever got big!

**Comment by jonathantompson** [comment]
Just adding a comment to a super old issue.  I use the following function (cleanupModel) before saving to disk:

```
function zeroDataSize(data)
  if type(data) == 'table' then
    for i = 1, #data do
      data[i] = zeroDataSize(data[i])
    end
  elseif type(data) == 'userdata' then
    data = torch.Tensor():typeAs(data)
  end
  return data
end

-- Resize the output, gradInput, etc temporary tensors to zero (so that the on disk size is smaller)
function cleanupModel(node)
  if node.output ~= nil then
    node.output = zeroDataSize(node.output)
  end
  if node.gradInput ~= nil then
    node.gradInput = zeroDataSize(node.gradInput)
  end
  if node.finput ~= nil then
    node.finput = zeroDataSize(node.finput)
  end
  -- Recurse on nodes with 'modules'
  if (node.modules ~= nil) then
    if (type(node.modules) == 'table') then
      for i = 1, #node.modules do
        local child = node.modules[i]
        cleanupModel(child)
      end
    end
  end
  collectgarbage()
end
```

**Comment by n3011** [comment]
@jonathantompson hi could you please help me out here to compress my model.t7 file using this code. I am unable to do it.
