### ISSUE TITLE
Bug in Reshape.lua?

### ISSUE THREAD

**Issue by schaul** [torch/DEPRECEATED-torch7-distro#5]
It appears that the backward pass of the reshape module is incorrectly assuming that its input is contiguous.

In my tests, this fixes the problem:
https://github.com/schaul/torch/commit/8208b4a41c878478db948306858960ff186cbdaf

**Comment by andresy** [comment]
Hi Tom,

Thanks, I changed it in the master.

Note however that this contiguous assumption might be present in a lot of modules -- in general the 'gradOutput' comes from a 'gradInput' of another module (which is always contiguous when created by the nn module), so I did not pay too much attention there. One day I will have to do a pass over these.

Cheers
Ronan
