### ISSUE TITLE
what is the best way to multi-thread code?

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#50]
what is the best way to use more that one core?
running this code I am only using one core:

for t = 1,testData:size() do
   testData2.data[t] = l1net:forward(testData.data[t]:double())
end

I tried to change it to use more cores:

for t = 1,testData:size(),4 do
   testData2.data[t] = l1net:forward(testData.data[t]:double())
   testData2.data[t+1] = l1net:forward(testData.data[t+1]:double())
   testData2.data[t+2] = l1net:forward(testData.data[t+2]:double())
   testData2.data[t+3] = l1net:forward(testData.data[t+3]:double())
end

but this still uses only one core
what is the way to run more things in parallel?

**Comment by andresy** [comment]
i suppose that right now the best way is the parallel package from Clement
https://github.com/clementfarabet/lua---parallel

we are working on making torch7 more thread-safe, such that other lua pthread packages might work later...

**Comment by culurciello** [comment]
I believe this package is now integral part of torch already with :
torch.setnumthreads(params.threads)
I was setting threads numbers, and it works in some training steps, but not in the example above.

**Comment by andresy** [comment]
no, the torch.setnumthreads relates only to thread-enabled routines, such as certain neural network layers or other functions in the TH library (including BLAS functions).

**Comment by culurciello** [comment]
Hi guys, I am trying to figure out what is the best way to parallelize on multiple cores a simple FOR loop (as the one below). I have tried to look into the package "parallel", but there is no simple example of how to do this. In Parallel it looks like I would have to send each operation of the FOR loop separately to workers, but that might add too much communication delay. Here what I want to do is to run 4+ cores on the same data structure, but different portions of it. How do you suggest doing it? Thanks

```
  for t = 1, trainData:size() do
     trainData2.data[t] = dosomething...
  end
```

**Comment by culurciello** [comment]
anyone home on this issue? pls

**Comment by koraykv** [comment]
Unfortunately there is no simpler way than parallel package right now.

**Comment by culurciello** [comment]
thank you guys. The question is if parallel copies all the data again and send it to workers. It seem like it, need to do some test. I would not want the overhead of copying data reducing the benefits of multiple cores/threads.
