### ISSUE TITLE
"expand" function help

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#51]
function Tensor.expand(tensor,...)
does not have an help function and is not mentioned in:
http://www.torch.ch/manual/torch/tensor

same for
Tensor.expandAs

why?

**Comment by jucor** [comment]
There seem to be several undocumented functions such as this one, e.g.  [issue #83](https://github.com/andresy/torch/issues/83) about dok.unpack(). I realize writing the doc is lengthy: how can we contribute? Is there a repo for the doc, that we could fork from and request pulls to?

**Comment by clementfarabet** [comment]
Gents, indeed writing doc is painful. For now, all the doc is written in dokuwiki format. You can find it for each module in a dok/ directory (e.g. pkg/torch/dok/). Feel free to edit / extend these docs, it would definitely help us.

**Comment by jucor** [comment]
Brilliant! That way we can draft a bit of it as we stumble on things -- might not be as detailed as the doc you wrote so far, but that'll be a start.
