### ISSUE TITLE
nn.Square seems to compute gradInput of 1D vectors incorrectly

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#52]
It seems as if nn.Square fails to multiply the gradOutput \* input by 2 when operating on 1D vectors.  This seem apparent in the code, which I've copied below, although I must admit I have difficulty reading the C code underlying Torch.  Note that test.lua only tests three-dimensional inputs.  When the same test is run on one-dimensional inputs, nn.Square fails.

 if (input->nDimension == 1 || 
      !THTensor_(isContiguous)(input) || 
      !THTensor_(isContiguous)(gradOutput) ||
      !THTensor_(isContiguous)(gradInput))
  {
    TH_TENSOR_APPLY3(real, gradInput, real, gradOutput, real, input,  \
         _gradInput_data  = (_gradOutput_data) \* (_input_data););
  }
  else
  {
    real_ gradOutput_data = THTensor_(data)(gradOutput);
    real\* gradInput_data  = THTensor_(data)(gradInput);
    real\* input_data  = THTensor_(data)(input);
    long i;
# pragma omp parallel for private(i)

```
for(i = 0; i < THTensor_(nElement)(gradInput); i++)
  gradInput_data[i] = 2.0 * gradOutput_data[i] * input_data[i];
```

  }

**Comment by koraykv** [comment]
Thanks a lot! I corrected it.
