### ISSUE TITLE
[Doc] accUpdateGradParameters

### ISSUE THREAD

**Issue by schaul** [torch/DEPRECEATED-torch7-distro#53]
The doc currently states that accUpdateGradParameters does _two_ things at once, but in fact it does _three_, namely:

 accUpdateGradParameters(input, gradOutput, learningRate) = 
 accGradParameters(input, gradOutput)
 updateGradParameters(learningRate)
 zeroGradParameters()

(well, almost: the accumulation is not retained for the future, but the gradParameters are also not explicitly set to zero).

This could be clarified.

**Comment by clementfarabet** [comment]
Thanks for this, I've added a little sentence to the doc.
