### ISSUE TITLE
Compilation error?

### ISSUE THREAD

**Issue by schaul** [torch/DEPRECEATED-torch7-distro#56]
I needed the following change for torch to compile properly: 
https://github.com/schaul/torch/commit/45d162031711195548ecc1caf2be1899910c87d7

(w was undefined)

A bug or a dependency issue?

**Comment by pflaquerre** [comment]
This was merged in from another pull request earlier today: https://github.com/andresy/torch/pull/54. Nice timing :).

**Comment by schaul** [comment]
Great minds... :-)
