### ISSUE TITLE
build error - help?

### ISSUE THREAD

**Issue by jaberg** [torch/DEPRECEATED-torch7-distro#6]
Following the instructions here:
https://github.com/clementfarabet/torch7-demos

I had to manually add -fPIC to the CFLAGS in the lua makefile, but then it seemed to go ok... until

$ luarocks install torch

But now I'm stuck at

[ 93%] Built target libqttorch
make[2]: **\* No rule to make target `cuda/lib/THC/generic/THStorage.h', needed by`cuda/lib/THC/./THC_generated_THC.cu.o'.  Stop.
make[1]: **\* [cuda/lib/THC/CMakeFiles/THC.dir/all] Error 2
make: **\* [all] Error 2

**Comment by clementfarabet** [comment]
The -fpic flag is indeed missing for linux builds, thanks for pointing this out.

We have a cmake bug in torch, which can be circumvented, for now, by getting the torch sources and building them locally:

git clone https://github.com/andresy/torch.git
cd torch
luarocks make

# will crash at some point

cmake .
make install

# should pass this time :-)

We'll fix this soon.

**Comment by jtbates** [comment]
Clement, I am able to compile using your suggestion and I can use the torch module.  However, now I cannot install any modules that have torch as a dependency using 'luarocks install foo'.  Must I use the above method for each of these modules as well, or is there a workaround to get luarocks to recognize torch is installed?

**Comment by clementfarabet** [comment]
Ah. This cuda problem is really annoying. If it built the second time, you need to re-issue a: luarocks make. That will register torch as a lua 'rock'. Once it's registered, then all the other rocks should install properly.
