### ISSUE TITLE
nn.Power and nn.CMulTable incorrectly generate nans in gradInput if the input contains any zeros

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#60]
nn.Power and nn.CMulTable attempt to efficiently calculate the backpropagated gradient by dividing the module's output by its input.  This works under most circumstances, but incorrectly computes 0/0 = nan when an input is zero, whereas gradInput should be 0.

**Comment by koraykv** [comment]
I think this is correct, as far as I know IEEE754 specifies 0/0 as NaN.

**Comment by rolfe** [comment]
Certainly 0/0 is supposed to be nan.  However, the issue is how to compute d(x^n)/dx = n_x^(n-1) or d(x_y_z)/dx = y_z when x = 0.  The true value of the derivatives are 0 and y_z respectively.  However, if you first compute f(x) = x^n and then df/dx = n_f(x)/x or g(x,y,z) = x_y_z and then dg/dx = g(x)/x, you will incorrectly produce nans for the derivatives.  The current code for nn.Power and nn.CMulTable is making exactly this mistake.

**Comment by rolfe** [comment]
I've written up safe versions of these modules, which produce the correct output when the input is zero, but they're less efficient, since they compute the gradient in the most straightforward way possible.

**Comment by koraykv** [comment]
Another safe way would be to add a bias like 1e-12 to the input

**Comment by clementfarabet** [comment]
I like that better, it will be much faster.
