### ISSUE TITLE
string.gsub not found:

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#63]
Try the IDE: torch -ide
Type help() for more info
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
Lua 5.1  Copyright (C) 1994-2008 Lua.org, PUC-Rio
t7> require 'nnx'
t7> a = nn.Sequential()
t7> a:add(nn.Tanh())
t7> =a
error calling 'print' (/usr/local/share/torch/lua/nn/Sequential.lua:131: attempt to call method 'gsub' (a nil value))
t7>

**Comment by koraykv** [comment]
Can you try it with require 'nn', not require 'nnx'.

**Comment by clementfarabet** [comment]
It does the same in 'nn'. I'm afraid the new changes in the ID api were a bit aggressive: the torch objects are not userdata anymore it seems, but simple tables...

**Comment by clementfarabet** [comment]
This actually break all sorts of other subtle things.

**Comment by koraykv** [comment]
oopsie

**Comment by clementfarabet** [comment]
OK basically none of the meta functions work anymore: **tostring**, **call** ... All these guys are gone. That breaks all the printing, and possibly more things.

**Comment by andresy** [comment]
(1) Torch objects have been always either userdata (like Tensors) or tables (like nn stuff). This makes the job of luaT quite subtle.
(2) The bug was in fact quite small in terms of code: the operator functions were not returning the right number of returned elements.

Now fixed.

**Comment by culurciello** [comment]
Thank you for this!!!

Euge ~
