### ISSUE TITLE
Ambiguous constructors for torch.Tensor(LongStorage)

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#65]
There seem to be two constructors that are compatible with torch.Tensor(LongStorage).  The LongStorage could be interpreted as a list of sizes, and used to allocate an uninitialized tensor of the appropriate dimensions, or the LongStorage could be interpreted as the Storage underlying a Tensor, and used to initialize a Tensor that views this Storage directly.  Torch seems to choose the first of these options, but both seem to be compatible with the documentation, and the second would be convenient to find the minimum dimension of a tensor with the command torch.Tensor(my_tensor:size()):min(), where my_tensor is Tensor.

**Comment by koraykv** [comment]
I think the confusion _only_ occurs when the default tensor type is LongTensor. Otherwise a torch.Tensor is just a pointer for torch.DoubleTensor.

**Comment by rolfe** [comment]
torch.Tensor only refers to the Storage default type, rather than any Storage type?  That makes things more clear.  So if I wanted to wrap a tensor around the return value from a call to size(), I would need to use torch.LongTensor(my_tensor:size()):min()?  But then this is ambiguous, right?

**Comment by koraykv** [comment]
For example:

t7> x=torch.rand(10,10,2,5)
t7> =x:size()

 10
 10
  2
  5
[torch.LongStorage of size 4]

Here is how you would get the min dim of a tensor.

t7> return torch.LongTensor(x:size()):min()
2

OR

t7> return torch.min(torch.Tensor(x:size():totable()))
2

**Comment by rolfe** [comment]
Thanks.  That makes things clearer.  As a side point, torch.Storage.totable() appears to be undocumented.

**Comment by andresy** [comment]
ach, yes, there are several of these that i should put in documentation!
