### ISSUE TITLE
Module:getParameters incorrectly throws a 'weird parameters' error when parameters are shared

### ISSUE THREAD

**Issue by rolfe** [torch/DEPRECEATED-torch7-distro#66]
The Module:getParameters() method (and its redefinition in hessian.lua) checks that the total number of parameters in a module is equal to the size of the flattened parameter tensor.  However, the flattened parameter tensor only includes a single copy of each set of shared parameters.  In contrast, the total parameter count produced by the code

local nParameters = 0
for k,param in ipairs(parameters) do
    nParameters = nParameters + param:nElement()
end

counts every copy of shared parameters.  As a result, the total parameter count does not match the flattened parameter count when parameters are shared, and the error 'flattenParameters(): weird parameters' is incorrectly thrown.

**Comment by clementfarabet** [comment]
Hi Jason, I think you might still be using an old version of the code: the "weird parameters" message is now completely gone. Check out the new implementation here:
https://github.com/andresy/torch/blob/master/extra/nn/Module.lua#L152
