### ISSUE TITLE
dokindex.lua is not thread-safe

### ISSUE THREAD

**Issue by pflaquerre** [torch/DEPRECEATED-torch7-distro#7]
I've been building torch 7 with the following:

> cd torch7
> mkdir -p ./{build,install}.dbg
> pushd build.dbg
>   cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install.dbg -DINTEL_COMPILER_DIR=/opt/intel/Compiler/11.1/069/ ..
>   make -j12 install
> popd

but sometimes (not always) end up with a corrupted build.dbg/dokindex.lua:

> sections["Introduction"] = {rank=0, packages={}}
> s["Introduction"].packages["install"] = {title="Installation Instructions", rank=1}
> sections["QT Interface"].packages["qt"] = {title="Lua executable and QT classes generic interface", rank=1}
> sections["QT Interface"].packages["qtide"] = {title="QT IDE for Lua", rank=111111}

If you look at scripts/dokindex.lua, you'll see that everyone could be writing to dokcurrentindex at the same time:

> local f = io.open(dokcurrentindex)
> if f then
>    dofile(dokcurrentindex)
>    f:close()
> end
> 
> -- add new (given) section
> sections[section] = sections[section] or {rank=ranksec, packages={}}
> sections[section].packages[package] = {title=title, rank=rankpkg}
> sections[section].rank = math.min(sections[section].rank, ranksec)
> 
> -- write all the stuff on disk so we can reload it easily
> local f = io.open(dokcurrentindex, 'w')
> for secname, section in pairs(sections) do
>    f:write(string.format('sections["%s"] = {rank=%d, packages={}}\n', secname, section.rank))
>    for pkgname, package in pairs(section.packages) do
>       f:write(string.format('sections["%s"].packages["%s"] = {title="%s", rank=%d}\n', secname, pkgname, package.title, package.     rank))
>    end
> end
> f:close()

where dokcurrentindex is the same for most targets.

**Comment by andresy** [comment]
Ahum, yes, it is true, I knew it, and was surprised nobody complained before ;) I have to fix the problem, indeed, but I am not sure how (I thought about some lock file) -- thanks for the feedback.

**Comment by pflaquerre** [comment]
Looks like make has a NOTPARALLEL target for this: https://www.gnu.org/software/make/manual/html_node/Special-Targets.html. Otherwise, if you want to go the locking route, luaposix (https://github.com/rrthomas/luaposix) provides an interface to fcntl().

As a side note, I've also noticed intermittent build issues with cuda:

> make[2]: **\* No rule to make target `cuda/pkg/cunn/generic/THStorage.h', needed by`cuda/pkg/cunn/.cunn_generated_init.cu.o'.  Stop.
> make[1]: **\* [cuda/pkg/cunn/CMakeFiles/cunn.dir/all] Error 2
> make[1]: **\* Waiting for unfinished jobs....

It usually goes away when building again. I'm not familiar with that part of torch, so I'm not sure if it's another concurrency issue.

**Comment by andresy** [comment]
> Looks like make has a NOTPARALLEL target for this: https://www.gnu.org/software/make/manual/html_node/Special-Targets.html.

Interesting. I wonder if cmake supports it.

> Otherwise, if you want to go the locking route, luaposix (https://github.com/rrthomas/luaposix) provides an interface to fcntl().

yeah, the only thing is i wanted to avoid having to rely on external packages during the compilation...

> As a side note, I've also noticed intermittent build issues with cuda:
> 
> > make[2]: **\* No rule to make target `cuda/pkg/cunn/generic/THStorage.h', needed by`cuda/pkg/cunn/.cunn_generated_init.cu.o'.  Stop.
> > make[1]: **\* [cuda/pkg/cunn/CMakeFiles/cunn.dir/all] Error 2
> > make[1]: **\* Waiting for unfinished jobs....
> 
> It usually goes away when building again. I'm not familiar with that part of torch, so I'm not sure if it's another concurrency issue.

it is annoying indeed, could not find yet what it is... cmake is so obscure sometimes. a workaround is doing a 'cmake . ; make [possibly make install]' in your build directory.

**Comment by andresy** [comment]
i tried to fix it by making dokindex targets depend on previous ones.
i could not make it crash before modifications on my computer, nor after... so let me know if on your side it is ok now!

**Comment by pflaquerre** [comment]
This seems to work so far. Thanks!

**Comment by andresy** [comment]
Today was my cmake day. I also spent time fixing the freaking $%^&*( FindCUDA. Downloaded the latest, fixed it myself.
