### ISSUE TITLE
SVM example in torch

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#70]
Hi,
does anyone have a 5 line example of setting up an SVM layer in torch? I cannot find this information anywhere and it is useful to have it in the tutorial I think.
Thank you

**Comment by culurciello** [comment]
anyone?

**Comment by koraykv** [comment]
You can checkout a new package torch-svm from https://github.com/koraykv/torch-svm

It provides, svmsgd and svmasgd from Leon Bottou (rewritten in torch) and interfaces to Liblinear and Libsvm.

It is not included in the list of packages for torch-pkg, so please follow installation instructions (just 3 steps). If there are any problems, please let me know.

**Comment by hainguyenct** [comment]
Hello, do you have a simple example for running this svm? thanks
