### ISSUE TITLE
dropouts

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#73]
Anyone coded dropouts in a simple convnet test/tutorial?
I will give it a try now if nothing exists

**Comment by clementfarabet** [comment]
Yep, I had included it in the tutorials, [here](https://github.com/clementfarabet/torch-tutorials/blob/master/5_newmodules/Dropout.lua). It's pretty simple, and you can change 'p' while training, or for testing.
