### ISSUE TITLE
SparseLinear seems to have a problem.

### ISSUE THREAD

**Issue by clementfarabet** [torch/DEPRECEATED-torch7-distro#75]
SparseLinear is screwed?

source code :  
require 'torch'
require 'nn'
module= nn.SparseLinear(10000,2)  -- 10000 inputs, 2 outputs
x=torch.Tensor({{1, 0.1},{2, 0.3},{10, 0.3},{31, 0.2}})
print(x)
module:forward(x)

result :  
t7> dofile('/home/pmume05/luatest/new-task1/test.lua')
  1.0000   0.1000
  2.0000   0.3000
 10.0000   0.3000
 31.0000   0.2000
[torch.DoubleTensor of dimension 4x2]
/usr/local/share/torch/lua/nn/SparseLinear.lua:37: index out of bound
stack traceback:
 [C](?): in function 'SparseLinear_updateOutput'
 /usr/local/share/torch/lua/nn/SparseLinear.lua:37: in function </usr/local/share/torch/lua/nn/SparseLinear.lua:36>
 (tail call): ?
 /home/pmume05/luatest/new-task1/test.lua:7: in main chunk
 [C](?): in function 'dofile'
 [string "dofile('/home/pmume05/luatest/new-task1/tes..."]:1: in main chunk

**Comment by paidi** [comment]
I think I've fixed this at https://github.com/paidi/torch/ and issued a pull request

**Comment by ylecun** [comment]
Has this been fixed in the main repo?

**Comment by soumith** [comment]
has not been pulled into master. it also needs some tests before being pulled as well.

**Comment by paidi** [comment]
I added some tests for the SparseLinear module in extra/nn/test/test.lua but can add more it they're not sufficient.

**Comment by andresy** [comment]
Hey

Paidi's fix is great, and I merged it. I also merge it into torch/nn repository. Please, please, please, never, never, never do a pull request again into torch-distro: it is meant to disappear. Do it instead in each sub-module of torch.

Cheers
