### ISSUE TITLE
Rectified linear Units

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#80]
I was trying to get a rectified linear unit going in Torch, as this:

model:add(nn.Abs())
model:add(nn.SoftShrink(0)) -- these Abs+Hardshrink is basically a rectified linear unit

Did anyone play with this nonlinear function? Hinton group uses it heavily.
Any comments?
E

**Comment by soumith** [comment]
duplicate issue. should be closed.
