### ISSUE TITLE
dok.unpack() never mentioned in torch's online help?

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#83]
The function dok.unpack() shipped with torch can be tremendously useful for automatic documentation, yet I haven't seen it mentioned anywhere in torch's online documentation. Is it on purpose ?

I stumbled unto its use by image.display() shipped with 'image', which is in itself a great example on how to use it:

```
local function display(...)
   -- usage
   local _, input, zoom, min, max, legend, w, ox, oy, scaleeach, gui, offscreen, padding, symm, nrow, saturate = dok.unpack(
      {...},
      'image.display',
      'displays a single image, with optional saturation/zoom',
      {arg='image', type='torch.Tensor | table', help='image (HxW or KxHxW or Kx3xHxW or list)', req=true},
      {arg='zoom', type='number', help='display zoom', default=1},
      {arg='min', type='number', help='lower-bound for range'},
      {arg='max', type='number', help='upper-bound for range'},
      {arg='legend', type='string', help='legend', default='image.display'},
      {arg='win', type='qt window', help='window descriptor'},
      {arg='x', type='number', help='x offset (only if win is given)', default=0},
      {arg='y', type='number', help='y offset (only if win is given)', default=0},
      {arg='scaleeach', type='boolean', help='individual scaling for list of images', default=false},
      {arg='gui', type='boolean', help='if on, user can zoom in/out (turn off for faster display)',
       default=true},
      {arg='offscreen', type='boolean', help='offscreen rendering (to generate images)',
       default=false},
      {arg='padding', type='number', help='number of padding pixels between images', default=0},
      {arg='symmetric',type='boolean',help='if on, images will be displayed using a symmetric dynamic range, useful for drawing filters', default=false},
      {arg='nrow',type='number',help='number of images per row', default=6},
      {arg='saturate', type='boolean', help='saturate (useful when min/max are lower than actual min/max', default=true}
   )

--- etc etc
end
```

**Comment by clementfarabet** [comment]
Indeed, dok.unpack() is extremely useful. It came later, and was originally provided by one of my external packages (xlua, from memory). We're planning on a new version of dok.unpack(), which will get compiled to avoid the lengthy interpretation at runtime (right now, dok.unpack() is a bit slow. It doesn't matter for a function like display(), but it matters if we want to use it aboslutely everywhere.).

**Comment by jucor** [comment]
Makes a lot of sense. I was thinking: besides generating the usage string, can it be used to generate offline help at the same time ? A bit in the same way that Javadoc comments are parsed automatically by some IDEs ?

Actually, going that way: I notice you have a "@param" function in some of your code. Have you tinkered with Doxygen for lua ? Could we imagine using Doxygen-style comments which would be parsed automatically **at compilation time** to generate the usage string (i.e.: no need for an explicit function call at runtime), and would also be parsed to generate the offline doc (i.e. not having to maintain the reference manual in a separate place) ?

**Comment by andresy** [comment]
- In the upcoming version of torch, a good part of the doc will be generated from to what you give to dok.unpack() (well, the name will be revisited). (Of course, it will not be the only way to generate doc).
- Simply parsing things like "@param" in the doc does not provide us enough flexibility to generate the right function header. (Well, it could, but it would be so messy to cover all the cases we have to deal with, that I won't go in that direction).

**Comment by clementfarabet** [comment]
Julien, yes the @param are leftovers from a time where I was still trying to generate doc automatically (before dok.unpack appeared). As Ronan said, we're planning on moving towards something completely automated, completely based on dok.unpack().

**Comment by jucor** [comment]
Thanks Ronan and Clement. I'm looking forward to the automated doc :)
