### ISSUE TITLE
Tensor(storage) works differently for LongStorage than for its upper-class Storage.

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#84]
The constructor Tensor(storage) only works as expected for pure Storage, but not for LongStorage: in the latter case, it uses the LongStorage as a list of sizes, as opposed to returning a 1-D view of said storage.

Indeed  [the Tensor manual   for the constructor](http://www.torch.ch/manual/torch/tensor#torchtensor_storage_storageoffset_sz1_st1__sz4_st4) specifies that

```
If only storage is provided, it will create a 1D Tensor viewing the all Storage.
```

Indeed for Storage:

```
t7> return torch.Tensor(torch.Storage({2,3}))
 2
 3
[torch.DoubleTensor of dimension 2]

t7> 
```

However, for its specialized class LongStorage:

```
t7> return torch.Tensor(torch.LongStorage({2,3}))
-2.6816e+154 -2.6816e+154  6.9531e-310
  0.0000e+00   0.0000e+00  2.7813e-309
[torch.DoubleTensor of dimension 2x3]

t7> 
```

Is that on purpose ? I thought the class LongStorage was extending the class Storage, thus expected the same behaviour.

**Comment by andresy** [comment]
Because a lot of constructor variants have been added over time, we got a confusion between:
torch.Tensor(sizes, [strides])
torch.Tensor(storage, [storageOffset, sizes, [strides]])
... for the particular case of LongStorage.

I can't fix it in the current version of torch without breaking many things. It is fixed in the upcoming new torch version.

**Comment by andresy** [comment]
Ach, sorry, I misread.

In torch7, LongStorage is used to provide sizes, when you have more than 4 dimensions.

Thus, the first call corresponds to:
torch.Tensor(storage, [storageOffset, sizes, [strides]]) -- your storage and tensor type are identical
And the second:
torch.Tensor(sizes, [strides]) -- longstorage --> interpreted as sizes

As mentioned above, there is however an annoying confusion when using LongTensor with LongStorage.
Anyways, all this will be more clear soon (torch > 7).
