### ISSUE TITLE
MKL installation broke torch

### ISSUE THREAD

**Issue by culurciello** [torch/DEPRECEATED-torch7-distro#88]
After installing MKL and gcc 4.8 torch broke for me.
The problem seem to be here: /usr/local/share/lua/5.1/torch/init.lua

-- We are using paths.require to appease mkl
require "paths"
paths.require "libtorch"

Any idea, help?
thanks
E

see my errors below:

> > > /usr/local/share/lua/5.1/torch [master*]$ torch
> > > Try the IDE: torch -ide
> > > Type help() for more info
> > > Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
> > > torch-qlua: /usr/local/share/lua/5.1/torch/init.lua:4: cannot load '/usr/local/lib/lua/5.1/libtorch.dylib'
> > > stack traceback:
> > >     [C]: ?
> > >     [C]: in function 'require'
> > >     /usr/local/share/lua/5.1/torch/init.lua:4: in main chunk
> > >     [C]: in function 'require'
> > >     /usr/local/share/lua/5.1/torch-env.lua:238: in function 'loaddefaultlibs'
> > >     /usr/local/share/lua/5.1/torch-env.lua:248: in main chunk
> > >     [C]: in function 'require'
> > >     [string "require 'torch-env'"]:1: in main chunk

**Comment by culurciello** [comment]
can this be of importance?
-- Performing Test C_HAS_inline
-- Performing Test C_HAS_inline - Failed
-- Performing Test C_HAS___inline__
-- Performing Test C_HAS___inline__ - Failed
-- Performing Test C_HAS___inline
-- Performing Test C_HAS___inline - Failed
-- C inline seems not supported

**Comment by alexbw** [comment]
I'm having the same problem. I have Continuum.io's "Anaconda" Python package installed, which interfered with a qtlua install. I removed anaconda and the qtlua install worked. However, I think that the MKL install might still be a problem.

**Comment by soumith** [comment]
Are you using the ezinstall scripts to install torch?
