### ISSUE TITLE
torch.sum(x) and torch.sum(x,1) do not cast similary

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#95]
When summing a tensor of logical elements, specifying the dimension over which to operate to sum() causes a nice silent overflow error. Using sum() without a direction returns a double without such a problem. Explicit casting in sum-with-direction can avoid the overflow -- but hard to think of it when the overflow itself is silent. 

```
t7> y=torch.rand(1000):gt(.5) -- y is probably a ByteTensor
t7> =torch.sum(y) -- returns a double
494
t7> =torch.sum(y,1) -- returns a ByteTensor with the wrong result
 238
[torch.ByteTensor of dimension 1]

t7> return torch.sum(y:double(),1) -- returns a DoubleTensor
 494
[torch.DoubleTensor of dimension 1]
```

**Comment by andresy** [comment]
Indeed. There are a bunch of methods like this. In torch7 I was not particularly inclined to support cross-types functions -- I am still not: I am not sure I can choose for the user if he wants to sum using longs or ints, it might depends on some a priori on the data -- and then when it comes to functions like "mean", you might want to switch to doubles or floats.

It is actually in my todo list for the upcoming torch version, so suggestions are welcomed.

**Comment by jucor** [comment]
Happy new year! I haven't thought of the "ideal" conversion rules I'd love to see in there. However, whichever convention is chosen, I'd strongly suggest to ensure similar behaviour when called with and without dimension argument for 1-D vectors -- I think that otherwise could be a tricky source of bugs.
